name: simple_device_info_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  barcode_widget: ^2.0.4
  battery_info: ^1.1.1
  device_info_plus: ^9.0.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_login: ^4.1.1
  flutter_svg: ^2.0.7
  local_auth: ^2.1.6
  mobile_scanner: ^3.3.0
  nfc_manager: ^3.3.0
  provider: ^6.0.5
  sensors_plus: ^3.0.2
  syncfusion_flutter_charts: ^22.1.37

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icon/svg/
    - assets/icon/png/

fonts:
  - family: Comme
    fonts:
      - asset: assets/font/Comme-Regular.ttf
